### ISSUE TITLE
What’s the xcode version ?

### ISSUE THREAD

**Issue by Sobhi-IOS** [MuhammadAhmad665/ParallaxEffect#1]
<img width="913" alt="Screen Shot 2022-11-08 at 11 16 43 AM" src="https://user-images.githubusercontent.com/49310999/200524918-7cb06835-de3b-4e3f-be56-e8a566d06b7d.png">

my version Xcode 13.4.1 
this problem

**Comment by muhammadahmad665** [comment]
I am using Xcode 14.1
